### ISSUE TITLE
Autostart and activate adb after boot

### ISSUE THREAD

**Issue by stefanhuber** [thedroidgeek/oculus-wireless-adb#2]
Is it possible to run this app and activate wireless adb automatically after a new boot? Everything works fine until a reboot is done.

**Comment by Anthony-6** [comment]
Hello, any news about it ?

**Comment by ColinBou** [comment]
Hello I vote for this feature !

**Comment by Severem** [comment]
Does the Wireless ADB mode and .apk work with Meta Quest 3 headsets??  Perhaps a full demo of how to set all this up might alleviate the questions people have.  I know I am very interested in having this work.  This means I won't have to connect to my computer each and every time I load certain programs in my Meta.

**Comment by ShockedCoder** [comment]
> Is it possible to run this app and activate wireless adb automatically after a new boot?

AFAIK That's not possible unless you have root perms.

> Everything works fine until a reboot is done.

That happens because ADBs don't persist through reboots.

> Does the Wireless ADB mode and .apk work with Meta Quest 3 headsets??

It works with any android device.

> Perhaps a full demo of how to set all this up might alleviate the questions people have.

Paraphrasing the README:
 - Download the APK
 - Open command prompt and use `cd` to change your directory to the place where you downloaded it
 - Connect your Quest to your PC through USB
 - Execute the following commands:
   - `adb install app-debug.apk`
   - `adb shell pm grant tdg.oculuswirelessadb android.permission.WRITE_SECURE_SETTINGS`
   - `adb shell pm grant tdg.oculuswirelessadb android.permission.READ_LOGS`
 - That's it

To enable the tcpip 5555 mode:
 - `adb tcpip 5555`
 - Go into the app, turn the `tcpip 5555 mode` on
 - You're done.

**Comment by stefanhuber** [comment]
ok thanks @ShockedCoder, at least for USB connected adb it works fine after reboots.

**Comment by thedroidgeek** [comment]
This app only tells the system to enable the native ADB wireless functionality, so if triggered after boot (assuming you're already automatically connected to a WiFi network, which is a requirement to enable the service), it would show the system prompt to accept running the service in the current WiFi network, which would require wearing the headset anyway.

I therefore don't see a valid need for this feature, especially considering that a long USB-C cable would work a lot better for use cases where frequent reboots are needed.
